export const products = [
    {
      id: 0,
      title: "Samsung S21",
      description: "black in color",
      price: "25000",
      img: "https://images.pexels.com/photos/404280/pexels-photo-404280.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
      quantity: 0,
      detail: "iPhone 11 has nearly every meaningful feature the iPhone 11 Pros have: the most powerful performance in any smartphone, a new ultra wide camera, night mode for better low-light photography, longer battery life than the previous generation, and all of the new features in iOS.",
    },
    {
      id: 1,
      title: "Samsung S31",
      description: "color is black",
      price: "35000",
      img: "https://images.pexels.com/photos/404280/pexels-photo-404280.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
      quantity: 0,
      detail: "iPhone 11 has nearly every meaningful feature the iPhone 11 Pros have: the most powerful performance in any smartphone, a new ultra wide camera, night mode for better low-light photography, longer battery life than the previous generation, and all of the new features in iOS.",
    },
    {
      id: 2,
      title: "Samsung M21",
      description: "white in color",
      price: "23000",
      img: "https://images.pexels.com/photos/47261/pexels-photo-47261.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
      quantity: 0,
      detail: "iPhone 11 has nearly every meaningful feature the iPhone 11 Pros have: the most powerful performance in any smartphone, a new ultra wide camera, night mode for better low-light photography, longer battery life than the previous generation, and all of the new features in iOS.",
    },
    {
      id: 3,
      title: "Redmi 9",
      description: "black in color",
      price: "35000",
      img: "https://images-na.ssl-images-amazon.com/images/I/71A9Vo1BatL._SL1500_.jpg",
      quantity: 0,
      detail: "iPhone 11 has nearly every meaningful feature the iPhone 11 Pros have: the most powerful performance in any smartphone, a new ultra wide camera, night mode for better low-light photography, longer battery life than the previous generation, and all of the new features in iOS.",
    },
    {
      id: 4,
      title: "Iphone 12",
      description: "Best mobile ever",
      price: "90500",
      img: "https://images-na.ssl-images-amazon.com/images/I/71hIfcIPyxS._SL1500_.jpg",
      quantity: 0,
      detail: "iPhone 11 has nearly every meaningful feature the iPhone 11 Pros have: the most powerful performance in any smartphone, a new ultra wide camera, night mode for better low-light photography, longer battery life than the previous generation, and all of the new features in iOS.",
    },
    {
      id: 5,
      title: "Samsung S21",
      description: "black in color",
      price: "25000",
      img: "https://images.pexels.com/photos/404280/pexels-photo-404280.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
      quantity: 0,
      detail: "iPhone 11 has nearly every meaningful feature the iPhone 11 Pros have: the most powerful performance in any smartphone, a new ultra wide camera, night mode for better low-light photography, longer battery life than the previous generation, and all of the new features in iOS.",
    },
    {
      id: 6,
      title: "Redmi 9",
      description: "black in color",
      price: "35000",
      img: "https://images-na.ssl-images-amazon.com/images/I/71A9Vo1BatL._SL1500_.jpg",
      quantity: 0,
      detail: "Samsung is the no. 1 smartphone brand followed by Huawei. Samsung leads the smartphone market in Pakistan. Other top smartphone brands in Pakistan are Huawei, Oppo, QMobile and Motorola.",
    },
    {
      id: 7,
      title: "Samsung S21",
      description: "black in color",
      price: "25000",
      img: "https://images.pexels.com/photos/404280/pexels-photo-404280.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
      quantity: 0,
      detail: "Samsung is the no. 1 smartphone brand followed by Huawei. Samsung leads the smartphone market in Pakistan. Other top smartphone brands in Pakistan are Huawei, Oppo, QMobile and Motorola.",
    },
    {
      id: 8,
      title: "Iphone 12",
      description: "Best mobile ever",
      price: "90500",
      img: "https://images-na.ssl-images-amazon.com/images/I/71hIfcIPyxS._SL1500_.jpg",
      quantity: 0,
      detail: "Samsung is the no. 1 smartphone brand followed by Huawei. Samsung leads the smartphone market in Pakistan. Other top smartphone brands in Pakistan are Huawei, Oppo, QMobile and Motorola.",
    },
    {
      id: 9,
      title: "Samsung S21",
      description: "black in color",
      price: "25000",
      img: "https://images.pexels.com/photos/404280/pexels-photo-404280.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
      quantity: 0,
      detail: "Samsung is the no. 1 smartphone brand followed by Huawei. Samsung leads the smartphone market in Pakistan. Other top smartphone brands in Pakistan are Huawei, Oppo, QMobile and Motorola.",
    },
  ];